### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by scollon42** [detectlanguage/detectlanguage-ruby#3]
Hi, thank you for your work! :)

My app raised this error sometimes when I use `DetectLanguage.detect` method.
I think it's the API that return unexpected format like empty array or empty body.
I will make a Pull request with this correction for this particular error, it might fix the error and return `nil` if the data is not well formated.

I can't see what string I send to the gem, The API seems to return at least `{"data":{"detections":[]}}` but maybe there is a special case.

```rb
def detect(data)
  key = data.is_a?(Array) ? 'q[]' : 'q'
  result = client.post(:detect, key => data)
  result.fetch('data', {}).fetch('detections', nil)
end
```

let me know if you have another idea or if this seems not good for you :)

(Sorry if my english is not correct)

**Comment by laurynas** [comment]
Hi @scollon42, thank you for your report. I will investigate it and will let you know.

**Comment by laurynas** [comment]
I think I have managed to reproduce the error you are getting like this:

```ruby
result = DetectLanguage.detect(["", "Hello"])

p result[1][0]['language'] # will work fine
p result[0][0]['language'] # will raise error
```
In this case `result[0]` is an empty array because no language could be detected. It is an expected case.

I suggest checking if result is not empty before trying to fetch a language.

**Comment by scollon42** [comment]
Hi ! Thanks for you quick answer ! 

I don't use array as an argument in the detect function, it's a simple string (I just don't know what contain the string).
First thing I did when I saw the error it's to fix my app and add some protection to prevent from nil or empty result but the error was still here.
Then I read more carefully the error and it was specificly on the line where I'm calling ` DetectLanguage.detect` function 
```rb
language_detection = DetectLanguage.detect body_sanitized
```
I made a little fix directly on my app by overriding the DetectLanguage module (detect function) with the code :
`result.fetch('data', {}).fetch('detections', nil)`
and it seems to work (I'm still monitoring this. If it happen again I will update the issue)

Sorry if I can't give you more precision on what type on string I send to the function I think it might be useful to figured out what special case we have here...

**Comment by scollon42** [comment]
If you think the error can come from a weird body return by the API, I can fork and pull request a fix with the fetch method and use webmock to add some more specific rspec.

**Comment by laurynas** [comment]
Hey, I will investigate it further later. I guess it has something to do with body and not detecting a language (empty result).

**Comment by scollon42** [comment]
Yes I was not able to reproduce the empty body with curl and the API but I think this is what happened.
Tell me if you need more informations or if you need help to figured out what happened.

**Comment by laurynas** [comment]
@scollon42, I can't reproduce the issue. If it has something to do with the response body, then your suggested code would solve the problem. But I think it would be better to find the real issue causing body error (handling this case with empty response would hide the problem). 

It would be very helpful if you could catch the request params triggering this issue. Maybe you could rescue the exception and log what what text was provided to the detector?

**Comment by scollon42** [comment]
I haven't seen this error since I override the detect methods. But I'm agree with you, the real issue would be a better help for a good fix. I'll add some logs to monitor what issue it could be and add the result here :smile:
