### ISSUE TITLE
(DetectLanguage::Error) "Failure: Net::HTTPPaymentRequired"

### ISSUE THREAD

**Issue by huzhijia** [detectlanguage/detectlanguage-ruby#4]
hi,

Please help me, I found this error recently.

` info = DetectLanguage.detect(content)`

**Comment by laurynas** [comment]
402 Payment Required exception is raised when account is temporary suspended because of going over your plan's daily detections limit. It can be unsuspended by logging into detectlanguage.com dashboard and switching the plan.
